#!/usr/bin/perl -w

# Citrocan
# Copyright (c) 2016 sisoftrg
# The MIT License (MIT)

use Time::HiRes qw/gettimeofday/;

$port="/dev/rfcomm0";
$speed=460800;

$|=1;
open P,"+<$port" or die $!;
system "stty -F $port ispeed $speed ospeed $speed -isig -icanon -iexten -echo -echoe -echok -echoctl -echoke ignbrk -brkint -icrnl -imaxbel min 1 time 5";

sub getb {
    my($a);
    sysread P,$a,1 or die $!;
    my($b)=unpack('C1',$a);
    return $b;
}

sub putb {
    my($a)=pack('C1',$_[0]);
    syswrite P,$a,1 or die $!;
}

sub puts {
    syswrite P,$_[0]."\r\n" or die $!;
}

#puts("i1");

$buf='';
while(1) {
    my($ev)=getb();
    if($ev == 10) {
	print gettimeofday()." $buf\n" if $buf;
	$buf = '';
    } elsif($ev != 13) {
	$buf = $buf . chr($ev);
    }
}
